/**
 * generated by Xtext 2.12.0
 */
package fr.ice.m1.fsm.ui.contentassist;

import fr.ice.m1.fsm.ui.contentassist.AbstractFSMProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class FSMProposalProvider extends AbstractFSMProposalProvider {
}
