/**
 * generated by Xtext 2.12.0
 */
package fr.ice.m1.fsm.validation;

import fr.ice.m1.fsm.validation.AbstractFSMValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class FSMValidator extends AbstractFSMValidator {
}
