/**
 * generated by Xtext 2.12.0
 */
package fr.ice.m1.fsm.ui;

import fr.ice.m1.fsm.ui.AbstractFSMUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class FSMUiModule extends AbstractFSMUiModule {
  public FSMUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
