/**
 * generated by Xtext 2.12.0
 */
package fr.ice.m1.fsm.ide;

import fr.ice.m1.fsm.ide.AbstractFSMIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class FSMIdeModule extends AbstractFSMIdeModule {
}
