/*
 * generated by Xtext 2.12.0
 */
package fr.ice.m1.fsm.ide

import com.google.inject.Guice
import fr.ice.m1.fsm.FSMRuntimeModule
import fr.ice.m1.fsm.FSMStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class FSMIdeSetup extends FSMStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new FSMRuntimeModule, new FSMIdeModule))
	}
	
}
