/*
 * generated by Xtext 2.12.0
 */
package fr.ice.m1.fsm.ui.tests;

import com.google.inject.Injector;
import fr.ice.m1.fsm.ui.internal.FsmActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class FSMUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return FsmActivator.getInstance().getInjector("fr.ice.m1.fsm.FSM");
	}

}
