/*
 * generated by Xtext 2.12.0
 */
package fr.ice.m1.fsm


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class FSMRuntimeModule extends AbstractFSMRuntimeModule {
}
