/*
 * generated by Xtext 2.12.0
 */
package fr.ice.m1.fsm


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class FSMStandaloneSetup extends FSMStandaloneSetupGenerated {

	def static void doSetup() {
		new FSMStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
