/**
 * generated by Xtext 2.12.0
 */
package fr.ice.m1.fsm.scoping;

import fr.ice.m1.fsm.scoping.AbstractFSMScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class FSMScopeProvider extends AbstractFSMScopeProvider {
}
