/*
 * generated by Xtext 2.12.0
 */
package fr.ice.m1.fsm.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractFSMScopeProvider extends DelegatingScopeProvider {
}
