/*
 * generated by Xtext 2.12.0
 */
package fr.ice.m1.fsm.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class FSMAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("fr/ice/m1/fsm/parser/antlr/internal/InternalFSM.tokens");
	}
}
