/*
 * generated by Xtext 2.12.0
 */
package fr.ice.m1.fsm.parser.antlr;

import com.google.inject.Inject;
import fr.ice.m1.fsm.parser.antlr.internal.InternalFSMParser;
import fr.ice.m1.fsm.services.FSMGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class FSMParser extends AbstractAntlrParser {

	@Inject
	private FSMGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalFSMParser createParser(XtextTokenStream stream) {
		return new InternalFSMParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "FSM";
	}

	public FSMGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(FSMGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
