/**
 * generated by Xtext 2.12.0
 */
package fr.ice.m1.fsm;

import fr.ice.m1.fsm.AbstractFSMRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class FSMRuntimeModule extends AbstractFSMRuntimeModule {
}
