/**
 * generated by Xtext 2.12.0
 */
package fr.ice.m1.fsm;

import fr.ice.m1.fsm.FSMStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class FSMStandaloneSetup extends FSMStandaloneSetupGenerated {
  public static void doSetup() {
    new FSMStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
